### ISSUE TITLE
Tutorial how to install & use

### ISSUE THREAD

**Issue by greenkohl23** [StoyanDimitrov/friendstatstic#1]
Hi, 
is there any tutorial how to use this chrome extension?

**Comment by StoyanDimitrov** [comment]
Hey,
Indeed the use of it is not obvious. I'll add documentation.

**Comment by StoyanDimitrov** [comment]
I just remembered that Inno made an change in one of the responses that makes the use of this extension a pain. It is still usable, but have to step manually through all pages of the actions history (what was the name?).
